version: '3.8'

services:
  grafana:
    image: grafana/grafana
    network_mode: host
    volumes:
    - ./volumes/grafana/data:/var/lib/grafana grafana/grafana

# docker run -d --name=grafana -p 3000:3000 grafana/grafana